### ISSUE TITLE
Where is a prebuild deb?

### ISSUE THREAD

**Issue by TriMoon** [bluca/razercfg-debian#1]
I came here from https://github.com/mbuesch/razer/issues/66

It still is not available at Debian, see: https://packages.debian.org/search?keywords=razercfg&searchon=names&suite=all&section=all

I have a Razer Naga Hex, and would like to use this software :wink: 
Is it possible for you to build a .deb for Debian 9 (sid) and make it available in the releases section of this git repo until it is added to Debian repos?
Thanks...

**Comment by bluca** [comment]
it's been in NEW for a while, I'll try and gently prod for news

**Comment by bluca** [comment]
It's been accepted, so it will be in sid tomorrow. Next week I'll upload to stretch-backports as well, so going to close this now.

**Comment by TriMoon** [comment]
Been a while and just checked again.
Yes it's now listed but has no files listed for any architecture, fe. this link gives an error page:
https://packages.debian.org/sid/amd64/razercfg/filelist

**Comment by bluca** [comment]
packages.debian.org is broken

**Comment by TriMoon** [comment]
oh ic
